from enum import Enum, StrEnum

class Status(Enum):
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    NOT_FOUND = 'NOT_FOUND'
    UNAUTHORIZED = 'UNAUTHORIZED'

class AuthStatus(Enum):
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'
    INVALID_TOKEN = 'INVALID_TOKEN'
    INVALID_USER = 'INVALID_USER'
    INVALID_PASSWORD = 'INVALID_PASSWORD'
    INVALID_EMAIL = 'INVALID_EMAIL'
    INVALID_USERNAME = 'INVALID_USERNAME'
    INVALID_ROLE = 'INVALID_ROLE'
    INVALID_STATUS = 'INVALID_STATUS'
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
    INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD'
    TOKEN_EXPIRED = 'TOKEN_EXPIRED'
    USER_NOT_FOUND = 'USER_NOT_FOUND'
    FORBIDDEN = 'FORBIDDEN'

class Roles(Enum):
    ADMIN = 'ADMIN'
    USER = 'USER'

class OrderStatus(StrEnum):
    PENDING = 'PENDING'
    PROCESSING = 'PROCESSING'
    APPROVED = 'APPROVED'
    WAITING_PAYMENT = 'WAITING_PAYMENT'
    PAID = 'PAID'
    ACTIVE = 'ACTIVE'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'

class BloodType(StrEnum):
    FIRST_POSITIVE = '1+'
    FIRST_NEGATIVE = '1-'
    SECOND_POSITIVE = '2+'
    SECOND_NEGATIVE = '2-'
    THIRD_POSITIVE = '3+'
    THIRD_NEGATIVE = '3-'
    FOURTH_POSITIVE = '4+'
    FOURTH_NEGATIVE = '4-'

class GenderType(StrEnum):
    MALE = 'M'
    FEMALE = 'F'