"""empty message

Revision ID: 9458cae38328
Revises: df5b4cf8f55a
Create Date: 2025-06-13 14:56:48.214337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9458cae38328'
down_revision: Union[str, None] = 'df5b4cf8f55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_diagnosis', sa.Column('id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('child_diagnosis', 'id')
    # ### end Alembic commands ###
