"""empty message

Revision ID: dd30f2d1a703
Revises: a2f8f47910a8
Create Date: 2025-06-13 14:59:38.241097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd30f2d1a703'
down_revision: Union[str, None] = 'a2f8f47910a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_diagnosis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_child', sa.Integer(), nullable=False),
    sa.Column('id_diagnosis', sa.Integer(), nullable=False),
    sa.Column('date_diagnosis', sa.Date(), nullable=False),
    sa.Column('doctor', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_child'], ['childs.id'], ),
    sa.ForeignKeyConstraint(['id_diagnosis'], ['diagnosis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('child_diagnosis')
    # ### end Alembic commands ###
